[versions]
compileSdk = "33"
minSdk = "23"
targetSdk = "33"

agp = "8.0.0"
accompanist = "0.15.0"
androidxlifecycle = "2.6.1"
androidxactivity = "1.7.0"
chucker = "3.5.2"
coil = "2.3.0"
compose-bom = "2023.03.00"
coroutines = "1.6.4"
kotlin = "1.8.20"
kotlininject = "0.6.1"
ktlint = "0.48.1"
composecompiler = "1.4.5"
okhttp = "5.0.0-alpha.7"
retrofit = "2.9.0"
dagger_hilt = "2.45"
firebase-bom = "31.0.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-dagger-hilt-library = { id = "com.google.dagger.hilt.android", version.ref = "dagger_hilt" }
android-dagger-hilt = { id = "dagger.hilt.android.plugin", version.ref = "dagger_hilt" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "2.7.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:1.8.20-1.0.10"
gms-googleServices = "com.google.gms.google-services:4.3.15"
firebase-crashlytics = "com.google.firebase.crashlytics:2.9.5"
[libraries]
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }

androidx-activity-activity = { module = "androidx.activity:activity", version.ref = "androidxactivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxactivity" }
androidx-archCoreTesting = "androidx.arch.core:core-testing:2.2.0"
androidx-browser = "androidx.browser:browser:1.5.0"
androidx-collection = "androidx.collection:collection-ktx:1.2.0"
androidx-core = "androidx.core:core-ktx:1.10.0"
androidx-emoji = "androidx.emoji:emoji:1.1.0"

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }

androidx-navigation-compose = "androidx.navigation:navigation-compose:2.6.0-alpha09"

androidx-palette = "androidx.palette:palette:1.0.0"

androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.0"


androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-benchmark-macro = "androidx.benchmark:benchmark-macro-junit4:1.2.0-alpha13"
androidx-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

androidx-work-runtime = "androidx.work:work-runtime-ktx:2.8.1"

appauth = "net.openid:appauth:0.8.1"

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

tools-desugarjdklibs = "com.android.tools:desugar_jdk_libs:2.0.3"

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-material-material3 = { module = "androidx.compose.material3:material3" }

compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

compose-ui-uitextfonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-dynamic-links = { module = "com.google.firebase:firebase-dynamic-links-ktx" }

androidx-hilt-navigationcompose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-hilt-work = "androidx.hilt:hilt-work:1.0.0"
junit = "junit:junit:4.13.2"

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-playservices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }

kotlininject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlininject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-json = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.10"

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

timber = "com.jakewharton.timber:timber:5.0.1"

dagger-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "dagger_hilt" }
dagger-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "dagger_hilt" }
